### ISSUE TITLE
Example with styled-components

### ISSUE THREAD

**Issue by correttojs** [Ergosign/storybook-addon-pseudo-states#23]
Does it support styled-components?
I see the `:hover` class is added to the element, but the state doesn't change

**Comment by philippone** [comment]
Hi @correttojs ,

I do not understand your problem. 
Could you describe it in more detail, please?

**Comment by correttojs** [comment]
I created a repo based on your react example, but using styled components instead of scss
https://github.com/correttojs/create-react-app-storybook-addon-pseuo-states

The button hover works, but the style doesn't apply to the storybook pseudos

<img width="433" alt="Screenshot 2020-09-22 at 13 08 41" src="https://user-images.githubusercontent.com/1736925/93875377-278ce480-fcd5-11ea-9d30-7de3fa31cd98.png">

<img width="368" alt="Screenshot 2020-09-22 at 13 08 52" src="https://user-images.githubusercontent.com/1736925/93875397-31164c80-fcd5-11ea-8209-791d5a0241e8.png">

**Comment by philippone** [comment]
Hi @correttojs ,

I guess the css-classes of your css-pseudo-states are not generated in the styled-components context.
The css-class (`\:hover`) is applied to the element but there is no css-class definition in your styling

![image](https://user-images.githubusercontent.com/1104798/94144836-f0076f00-fe71-11ea-84af-15f283688235.png)
 
Usually, the css-class (`\:hover`) is generated automatically from your css (`:hover`) during the webpack build process by chaining `post-css-loader` with [`postcss-pseudo-classes`-Plugin](https://github.com/giuseppeg/postcss-pseudo-classes) with `scss-loader` or `css-loader`. 

This processing step is missing.

The `post-css-loader` is added automatically to the webpack config when using the provided preset but it is not working for styled-components.

You could add the css-class selector manually. For instance: 

```
const ButtonStyle = styled.button`

  &:hover, &.\\:hover {
    background: green;
  };`
```

Unfortunately, these classes are also available in your build output.
 
Another solution is to add the described functionality but `post-css` seems not compatible:  
https://github.com/styled-components/styled-components/issues/482

**Comment by correttojs** [comment]
Thank you for the detailed answer, indeed I'm considering these options:
- explicitly define props to initialize the react components in a given css state
- adding the `&.\\:hover` class manually to each component
- implement the same solution using the babel plugin for styled components

**Comment by philippone** [comment]
Nice!

If you want to implement a babel plugin, let me know if I can help you.

**Comment by correttojs** [comment]
hi @philippone 

I created a draft of a babel plugin (https://github.com/correttojs/babel-plugin-styled-components-pseudo-states).
In the storybook I added a wrapped element with a fixed id (`StorybookWrapper`), so then the final css would be 
`
&:hover, #StorybookWrapper.\\:hover &{
 background: green;
}
`

Do you have a better suggestion to avoid creating this additional element? The hover state may be defined in a nested component, so `&.\\:hover` wouldn't reference the correct element.

Also, what kind of transformations would you suggest to add to the babel plugin? I need to add `:focus` and other pseudo classes, but do you think the transformation `css.replace(':hover', ':hover,&.\\:hover')` would cover every case?

I'm using chromatic to create a screenshot in a hovered state, and I noticed the `@media (hover: hover)` doesn't match, so I had to conditionally remove it using an environment variable. Did you face similar issues?

**Comment by philippone** [comment]
Hi @correttojs ,

I don't understand why you adding the wrapping element (`StroybookWrapper`)?

Your babel addon should alter the styling (css) output.

From 

```css
.my-component:hover {
   background: green;
}
```

to

```css
.my-component:hover, myComponent.//:hover {
   background: green;
}
```


My addon only applies this new (pseudo) class (`.//:hover`) to the component's DOM inside of storybook.
If the class should be applied to a nested element, you could specify by denoting `selector` in the addon's options. 

From

```html
<div class="my-component"></div>
```

to


```html
<div class="my-component :hover"></div>
```


The postcss equivalent to your babel plugin is 'postcss-pseudo-classes'. It uses a regex to match all pseudo states: https://github.com/giuseppeg/postcss-pseudo-classes/blob/master/index.js#L47

**Comment by correttojs** [comment]
what about a nested styled component child?

```
const ButtonComponent = ({text}) => (
  <MyButton> 
      <MyIcon><MyText>{text}</MyText></MyIcon>
   </MyButton> 
);

const MyButton = styled.button`
  width: 200px;
  height: 80px;
`;

const MyIcon = styled.div`
  width: 48px;
  height: 48px;
`;

const MyText = styled.span`
  &:hover{
      background-color: red;
  }
`;
```

where the storybook is defined on `MyButton` but `MyText` background changes hovering `MyIcon`.

Also the styled component reference would be harder to achieve https://styled-components.com/docs/advanced#referring-to-other-components

**Comment by philippone** [comment]
Hi @correttojs ,

> where the storybook is defined on MyButton but MyText background changes hovering MyIcon.

If it's realizable with styled components then it should work.

If I have more time next week I will try to develop/test the babel plugin
