### ISSUE TITLE
Error: "undefined is not an object (evaluating 'compInternal.selector')" with template strings

### ISSUE THREAD

**Issue by fredvisser** [Ergosign/storybook-addon-pseudo-states#29]
**Describe the bug**
Cannot create a story leveraging pseudo-states that uses template strings to define the story. Instead, we get an error `undefined is not an object (evaluating 'compInternal.selector')`

**To Reproduce**
Add the following to the [simple-button.stories.ts](https://github.com/philippone/angular-ci-storybook-pseudo-states-example/blob/master/src/app/components/buttons/simple-button/simple-button.stories.ts) story in the [angular-ci-storybook-pseudo-states-example](https://github.com/philippone/angular-ci-storybook-pseudo-states-example) –

```js
export default {
  title: "Simple Button",
  decorators: [
    withPseudo(),
    moduleMetadata({
        imports: [ButtonsModule] // Import the ButtonsModule so we can use the selector directly
    }),
    withKnobs
  ],
};

export const simpleButton3 = () => {
  return {
    template: `<app-simple-button [label]="'Button Text'"></app-simple-button>`,
  };
};
```

If I remove the `withPseudo()` decorator, the story renders correctly.

**Expected behavior**
Pseudo states enumerated for the component.

**Screenshots**
![Screen Shot 2020-09-28 at 4 07 36 PM](https://user-images.githubusercontent.com/1458528/94486382-f7e24e80-01a4-11eb-8d5e-af351d953f44.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome & Safari
 - Version: latest 

Very cool addon – Thanks!

**Comment by philippone** [comment]
Hi @fredvisser ,

thanks for your feedback.

It's already working when you specify the `component` in your story:

```js
export const simpleButton3 = () => {
  return {
    component: SimpleButtonComponent,
    template: `<app-simple-button [label]="'Button Text'"></app-simple-button>`
  };
};
```

Nevertheless, I try to find a solution to support only a `template`.

**Comment by philippone** [comment]
The `component` field is required because the component has to be added to the internal used module declaration.
