### ISSUE TITLE
Create React App support?

### ISSUE THREAD

**Issue by techieshark** [Ergosign/storybook-addon-pseudo-states#3]
This looks like a super useful addon. I'd love to use it.

**Is your feature request related to a problem? Please describe.**

I've tried to configure this but it seems not possible for those who are using Create React App (CRA) and have not ejected.

**Describe the solution you'd like**

Is it possible to document how to configure with CRA?

**Comment by philippone** [comment]
Hi @techieshark ,

thanks for your feedback. 

I'll try to find a solution.

**Comment by philippone** [comment]
Hello @techieshark ,

I have pushed some changes and released version [`v0.0.1-alpha.13`](https://github.com/Ergosign/storybook-addon-pseudo-states/releases/tag/v0.0.1-alpha.13)

Here you can find an example repo and the steps to integrate storybook and the add-on into CRA.
https://github.com/philippone/create-react-app-storybook-addon-pseuo-states#steps

If this is working for you too, I will add it to the documentation. 

Again, thanks for your feedback!

**Comment by techieshark** [comment]
Hi @philippone, thanks for that!
