### ISSUE TITLE
preset-postcss breaks exporting Sass constants

### ISSUE THREAD

**Issue by torkelrogstad** [Ergosign/storybook-addon-pseudo-states#31]
When adding `preset-postcss`, I can no longer use exported constants from Sass files. 

Reproduction: https://github.com/torkelrogstad/storybook-scss

1. in `src/styling.scss` i export a constant `foo`. 
2. in `src/stories/Button.stories.tsx` I try to access this constant in a story at the bottom of the file. 
3. Run `yarn storybook`, and observe that nothing is rendered. I would have expected an object with `foo` set to `#efabcd`

**Comment by philippone** [comment]
Hi @torkelrogstad ,

unfortunately your link is not working.

Could you provide an example, then I can test it. 

I'm not sure what you are trying to do 😅.

The preset should only add the `post-css-loader` with the `postcss-pseudo-classes` addon to the scss webpack rules.

**Comment by torkelrogstad** [comment]
Sorry, the repo was private! Made it public now.

**Comment by philippone** [comment]
Hi @torkelrogstad ,

a little bit late but I added `:export` to the disallowed selector list of the postcss-pseudo-classes addon by default and now it is working.
