### ISSUE TITLE
Failed to execute 'insertRule' on CSSStyleSheet error occurring for deep nested styles

### ISSUE THREAD

**Issue by sreeg123** [Ergosign/storybook-addon-pseudo-states#39]
**Describe the bug**
When ever we  have deep nested styles then Addon is throwing below error.
![image](https://user-images.githubusercontent.com/80047271/109980268-b44cbd00-7ccd-11eb-8dd2-b6adce9e0346.png)

**To Reproduce**
1. add .checkbox:hover:not(:active) and see error where checkbox class is on input type="checkbox"
2. even tried to change .checkbox\:hover:not(\:active) and i do not have luck
Note: after pseudo-state new rule :not() is invalid

I do not have any changes except adding   addons: [   
    'storybook-addon-pseudo-states',
     ] to main.js
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 88.0.4324.150

**Comment by philippone** [comment]
This [issue from postcss-pseudo-classes](https://github.com/giuseppeg/postcss-pseudo-classes/issues/16) should fix your issue too
