### ISSUE TITLE
Undeclared dependency on @storybook/node-logger

### ISSUE THREAD

**Issue by dobesv** [Ergosign/storybook-addon-pseudo-states#46]
**Describe the bug**

Yarn PnP requires projects to declare all their dependencies.  When trying to use this addon in a project that uses yarn pnp, it gives an error:

```
Error: @ergosign/storybook-addon-pseudo-states-react tried to access @storybook/node-logger, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by philippone** [comment]
Hi @dobesv ,

`@storybook/node-logger` is now declared as peer dependency.

Thank you for your feedback!
