### ISSUE TITLE
babel-plugin for emotion.js

### ISSUE THREAD

**Issue by pixelass** [Ergosign/storybook-addon-pseudo-states#50]
Not a feature but an FYI:

We just release a babel-plugin to support emotion.js: https://www.npmjs.com/package/babel-plugin-storybook-addon-pseudo-states-emotion

Live Demo: https://dekk-ui.dekk.app/?path=/story/design-system-atoms-button--pseudo-states

Is it ok to add this to the docs for React?

**Comment by philippone** [comment]
Hi @pixelass ,

that's very nice! 

Sure, let's add it to the docs.

**Comment by pixelass** [comment]
Thx, I'll prepare a PR for it.
