### ISSUE TITLE
classes do not persist after switching dark/light mode

### ISSUE THREAD

**Issue by pixelass** [Ergosign/storybook-addon-pseudo-states#51]
**Describe the bug**
When switching dark/light mode via https://storybook.js.org/addons/storybook-dark-mode the pseudo-classes do not persist.

**To Reproduce**
1. Go to https://dekk-ui.dekk.app/?path=/story/design-system-atoms-button--pseudo-states
2. Click on Toggle mode 
![Design_System___Atoms___Button_-_Pseudo_States_⋅_Storybook](https://user-images.githubusercontent.com/1148334/132039635-5273724d-312e-41ea-b67d-c5cd4226a610.png)

3. See error (styles/classes are not applied)

**Expected behavior**
The classes should still exist, The pseudo styles should work

**Screenshots**
![light-dark-mode_2](https://user-images.githubusercontent.com/1148334/132040489-708bf74e-d2e5-4764-b7e1-9fbdafc7295d.gif)

**Desktop (please complete the following information):**
 - OS: macOS (Version 11.5.2)
 - Browser Chrome (Version 92.0.4515.159)
 - Addon Version v0.0.1-alpha.47

**Comment by pixelass** [comment]
Looks like it works for permutations, but not for the default:

Screencast:

![permutations_pseudo-states](https://user-images.githubusercontent.com/1148334/132084291-1d742bdc-fd26-4035-af99-134fd52dde92.gif)

**Comment by philippone** [comment]
Hi @pixelass ,

it should now be working with the latest version v0.0.1-alpha.48.

Please have a try.

**Comment by pixelass** [comment]
Thx for the fast response. I can confirm that the update fixed the issue.
